services:
  nginx:
    image: nginx:alpine
    ports:  
    - 20000:80
    volumes:
      - ./dkr30-main/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - network
  mysql:
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: voting_user
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: voting_app
      MYSQL_PASSWORD: voting_pass
    volumes: 
      - mysql_data:/var/lib/mysql
    networks:
      - network
  redis:
    image: redis:alpine
    ports: 
      - 6379:6379
    volumes: 
      - redis_data:/data 
    networks:
      - network
  voting:
    build:
      context: ./dkr30-main
      dockerfile: Dockerfile
    environment:
      DB_HOST: mysql
      DB_DATABASE: voting_app
      DB_USERNAME: voting_user
      DB_PASSWORD: voting_pass
      REDIS_HOST: redis
      PHP_FPM_LISTEN: "0.0.0.0:9000"
      PHP_FPM_ALLOW: "any"
    command: >
      sh -c "sleep 10 && php artisan migrate --force && php artisan db:seed --force && php-fpm -F -R"
    ports: 
      - 9000:9000
    networks:
      - network
    depends_on:
      - mysql
      - redis

volumes:
  redis_data:
  mysql_data:

networks:
  network:
    driver: bridge

