#SPDX-License-Identifier: MIT-0
---
# tasks file for ssh
- name: Ensure group exists
  ansible.builtin.group:
    name: "{{ ssh_group }}"
    state: present

- name: Ensure user exists
  ansible.builtin.user:
    name: "{{ ssh_user }}"
    group: "{{ ssh_group }}"
    home: "{{ ssh_home }}"
    shell: /bin/bash
    create_home: yes
    state: present

- name: Ensure .ssh directory exists
  ansible.builtin.file:
    path: "{{ ssh_home }}/.ssh"
    state: directory
    owner: "{{ ssh_user }}"
    group: "{{ ssh_group }}"
    mode: "{{ ssh_dir_mode }}"

- name: Deploy SSH private key
  ansible.builtin.copy:
    content: "{{ ssh_private_key }}"
    dest: "{{ ssh_home }}/.ssh/id_ed25519"
    owner: "{{ ssh_user }}"
    group: "{{ ssh_group }}"
    mode: "{{ ssh_key_mode }}"
  when: ssh_private_key != "" 
  no_log: false
