---
run_git_clone: true
nodejs_version: "20.14.0"
git_branch: main
install_dir: "/opt/nodejs"
website_repo: "git@github.com:StrunetsD/nodejs-ansible-master.git"
#website_repo: "https://devops-gitlab.inno.ws/devops-board/nodejs-ansible.git"
website_dir: "/var/www/app"
master_ssh_private_key_path: ~/.ssh/id_rsa
master_ssh_public_key_path: ~/.ssh/id_rsa.pub
master_ssh_config_path: ~/.ssh/config

