FROM ruby:2.7

RUN apt-get update -qq && \
    # Установка зависимостей для nodesource
    apt-get install -y curl && \
    curl -sL https://deb.nodesource.com/setup_14.x | bash - && \
    # Основные системные зависимости
    apt-get install -y \
    build-essential \
    libpq-dev \
    nodejs \
    postgresql-client \
    imagemagick \
    ffmpeg \
    # Установка Yarn
    && npm install -g yarn@1.22.19 \
    # Очистка
    && apt-get remove -y curl \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app
ENV RAILS_ENV=development

COPY Gemfile Gemfile.lock ./
RUN bundle install --without production

COPY package.json yarn.lock ./
RUN yarn install

COPY . .

CMD ["rails", "server", "-b", "0.0.0.0"]